wazuh:
  image: "wazuh/wazuh:4.12.0"
  storage:
    size: 30Gi
    className: rook-ceph-block
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"

dashboard:
  image: "wazuh/wazuh-dashboard:4.12.0"
  storage:
    size: 30Gi
    className: rook-ceph-block
  resources:
    requests:
      cpu: "250m"
    limits:
      cpu: "500m"

indexer:
  image: "wazuh/wazuh-indexer:4.12.0"
  storage:
    size: 30Gi
    className: rook-ceph-block
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
